### ISSUE TITLE
Fix permission for starting servers on boot

### ISSUE THREAD

**Issue by wolpi** [wolpi/prim-ftpd#127]
currently there is an exception when trying to start servers on boot:

```
java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.BOOT_COMPLETED from pid=3870, uid=2000
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:3537)
        at com.android.commands.am.Am.sendBroadcast(Am.java:772)
        at com.android.commands.am.Am.onRun(Am.java:404)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:121)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
```

**Comment by wolpi** [comment]
actually it is still working, just commands to test it needed to be updated
