### ISSUE TITLE
// java.lang.NumberFormatException: Invalid int: ""

### ISSUE THREAD

**Issue by ape-report** [wolpi/prim-ftpd#131]
`Port` does not check empty input. `parseInt` should be used carefully.

```
// java.lang.NumberFormatException: Invalid int: ""
//  at java.lang.Integer.invalidInt(Integer.java:138)
//  at java.lang.Integer.parseInt(Integer.java:358)
//  at java.lang.Integer.parseInt(Integer.java:334)
//  at org.primftpd.prefs.PortEditTextPreference.onPreferenceChange(PortEditTextPreference.java:31)
//  at android.preference.Preference.callChangeListener(Preference.java:939)
//  at android.preference.EditTextPreference.onDialogClosed(EditTextPreference.java:145)
//  at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
//  at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1323)
//  at android.os.Handler.dispatchMessage(Handler.java:102)
//  at android.os.Looper.loop(Looper.java:148)
//  at android.app.ActivityThread.main(ActivityThread.java:5417)
//  at java.lang.reflect.Method.invoke(Native Method)
//  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
//  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by wolpi** [comment]
Oh, yes. Beginner mistake :innocent:

**Comment by wolpi** [comment]
should be fixed now
