### ISSUE TITLE
Question regarding to launch from external program

### ISSUE THREAD

**Issue by jingl3s** [wolpi/prim-ftpd#172]
Hello,

Thanks for this tool, I use it since some month and it is verify satisfying for basic purpose.

I want to use Automate from https://llamalab.com/automate/ in order to launch the SFTP server. Is like Tasker.

I tried to find out a way with adb shell in order to do that but I get stuck with too basic knowledge.

I tried using am command line like
adb shell am start -n org.primftpd/.PrimitiveFtpdActivity

It opens the application but I want to find a way to start the server.

The https://github.com/wolpi/prim-ftpd/blob/master/primitiveFTPd/AndroidManifest.xml does not permit me to do it.

Do you have some time to help me ?

AM documentation
https://developer.android.com/studio/command-line/adb#am

Thanks again for this amazing job for a tool that works in minutes.

**Comment by wolpi** [comment]
As you can see in #82 this app's tasker plugin does not work with automate.
There is a specialized activity to just launch the server, that might be what you need: `StartServerAndExitActivity`.

What do you mean with "the manifest does not permit to do it"? Is there an error message?

The approach with `adb` sounds interesting. But I think `adb` is available on computers only, not on android devices them self.

**Comment by jingl3s** [comment]
As I cannot figure out a solution from Automate. I tried a different path by using the and shell commands.

And I tried the StartServerAndExitActivity but does not seems to be recognized or I did not have setup the right information.

Thanks for pointing the other issue that seems look like my issue.

**Comment by wolpi** [comment]
When I try to launch `StartServerAndExitActivity` via `adb` I get this exception:
```
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=org.primftpd/.StartServerAndExitActivity } from null (pid=4661, uid=2000) not exported from uid 10085
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1788)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:717)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:544)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1099)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:486)

```
Probably that could be solved by configuring this activity for launching the app. But that would cause several activities to show up in main menu. This was done previously and users complained a lot.

You could try to see if there is a way to configure custom `Intent`s in automate.

**Comment by jingl3s** [comment]
I also tried the command StartServerAndExitActivity with AM command but I also added the user uid with option --user <UID> but no more success.
I think I can configure the intent but I did not know how to do that.

**Comment by wolpi** [comment]
Basically you could use an `Intent` to launch activity `org.primftpd/.StartServerAndExitActivity`

**Comment by jingl3s** [comment]
I also tried the command StartServerAndExitActivity with AM command but I also added the user uid with option --user <UID> but no more success.
I think I can configure the intent but I did not know how to use that as a command.

**Comment by wolpi** [comment]
You could use "App start":
![grafik](https://user-images.githubusercontent.com/1812560/60761340-743fbd80-a046-11e9-9dd7-1230325ca4b7.png)


And then select `org.primftpd/.StartServerAndExitActivity`

![grafik](https://user-images.githubusercontent.com/1812560/60761344-91748c00-a046-11e9-9b17-901124fecc46.png)

**Comment by jingl3s** [comment]
I tried that but with or without package setup I get the error 

> android.content.ActivityNotFoundException: No Activity found to handle the intent.

I also found there is a tasker/Locale plug-in but without success to start the server.

I tried on 2 phones one in Android 4.2 and other in Android 8.0 rooted.

Really thanks for trying helping me finding why is not working.

**Comment by wolpi** [comment]
As I learned there is a way to configure activities in manifest to be allowed to be launched by other apps while not showing them in menu. `StartServerAndExitActivity` has now been configured like this. And another activity has been added: `StopServerAndExitActivity`. This one might be useful for automation workflows, too.
These changes will be included in next version. Might take some more time until it is release.

**Comment by wolpi** [comment]
There is now a release ongoing ...

**Comment by lmagyar** [comment]
Just info for anybody who searches for this. To start/stop the server:
- `am start --user 0 -a android.intent.action.MAIN org.primftpd/.StartServerAndExitActivity`
- `am start --user 0 -a android.intent.action.MAIN org.primftpd/.StopServerAndExitActivity`

How many time I've wasted with am broadcast... :D
