### ISSUE TITLE
Installing 6.16 directly is missing the ActionBar on FireOS HD10

### ISSUE THREAD

**Issue by NgrNxk** [wolpi/prim-ftpd#297]
I installed 6.16 and had the same issue as in #278. The workaround didn't help: the ActionBar was there but clicking on "Einstellungen" crashed the app. I discovered that 6.15 worked just fine. Also after upgrading to 6.16 the ActionBar was present. But if you install 6.16 directly, it is missing.

**Comment by Xinaovo** [comment]
I found this problem on a Vivo Y51A(Snapdragon 410), running android 5.1, funtouch os 2.51 as well

**Comment by wolpi** [comment]
might be related to #257 or #281.

Can you share logs?

**Comment by Xinaovo** [comment]
@wolpi Sure, but I need you to tell me how to get those logs you need, by logcat?

**Comment by Xinaovo** [comment]
BTW, the app(6.15) doesn't work properly under Android 5.1, it will crash when you try to start the ftp server, under every modes. Maybe I can provide some logs about it for you.

**Comment by wolpi** [comment]
logcat is one of the options. By default the app does not log. You have to turn in on in preferences. Therefore you have to choose log target. Depending on that you have to use different tools to obtain logs.

**Comment by Xinaovo** [comment]
It seems there's nothing to do with logcat :) Vivo simply put those logs under /sdcard/bbk_log. Here are the logs:

2023-05-03 08:56:01
PD1510_C_4.22.0
versionName = 6.16 versionCode = 62
java.lang.NullPointerException	Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
KeysFingerprintsActivity.java	27
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.primftpd/org.primftpd.ui.KeysFingerprintsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
	at android.app.ActivityThread.access$900(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5401)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at org.primftpd.ui.KeysFingerprintsActivity.onCreate(KeysFingerprintsActivity.java:27)
	at android.app.Activity.performCreate(Activity.java:6074)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2392)
	... 10 more

**Comment by wolpi** [comment]
That is weird. This basically means there is an issue with your Android version. I can add a null check for such a case but it does not really make sense.


>It seems there's nothing to do with logcat 

You can configure this app to log to logcat.

**Comment by wolpi** [comment]
as UI code has been heavily changed with #281 it is most likely that this issue will be gone.
